### ISSUE TITLE
Sign In/Sign Up Page

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#2]
**Task title**
Sign In/Sign Up Page

**Task description**
Create a Sign In/Sign Up Page and its Components

**Subtasks**

1. Input Fields
 - Sign In
- [x] Email
- [x] Password 
 - Sign Up
- [x] Email
- [x] UserName
- [x] Password
- [x] Confirm Password
2. Button
- [x] Sign In
- [x] Sign Up
3. Links
- [x] Forget Password?
4. Social Sign-In Options
- [x] Google (Firebase)
5. Messages
- [x] Validation
- [x] Error
- [x] Success
6. Firebase
- [x] Auth
- [x] Firestore

**Link to the component on Figma**
[Figma component](https://www.figma.com/file/sDlEio3FtEwhvkQQyYJUZS/share-and-care?type=design&node-id=68-4057&mode=design&t=EfzNZY3MzXDepRr0-4)

**Comment by mouloud247** [comment]
All tasks are done.

**Comment by merzoukfatima** [comment]
brilliant mouloud
