### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#8]
**Task title**
Navbar
**Task description**
Create Navbar and its components

**Subtasks**
- [x] Logo
- Pages List
   - [x] Home #1 
   - [x] Meals #4 
   - [x] Blogs 
- [x] Cart 

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/Capstone-Dream-Team/assets/104175862/59ad7561-9440-41d3-8c2a-169d5d47546d)

**Link to the component on Figma**
[Navbar](https://www.figma.com/file/sDlEio3FtEwhvkQQyYJUZS/share-and-care?type=design&node-id=57-2516&mode=design&t=PEV1PhH2F1MLKJx8-4)

**Comment by ikoworld** [comment]
- [x] adding a user icon with dropdown list of options:
when the admin is not logged in:
1. sign in
2. sign up

when the admin is logged in :

1. dashboard
2. sign out
